// pwa/src/Search.svelte
<div class="container">
    <form>
        <div class="field is-horizontal">
            <div class="field-body">
                <div class="field">
                    <div class="control">
                        <input class="input" type="text" />
                    </div>
                </div>
                <div class="field is-grouped">
                    <div class="control">
                        <button class="button is-link">Search</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

// pwa/src/components/Search.vue
<template>
  <div class="container">
    <form>
      <div class="field is-horizontal">
        <div class="field-body">
          <div class="field">
            <div class="control">
              <input class="input" type="text" />
            </div>
          </div>
          <div class="field is-grouped">
            <div class="control">
              <button class="button is-link">Search</button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</template>
