// pwa/src/Toolbar.svelte
<script>
</script>

<div class="container">
    <div class="field is-grouped">
        <div class="navbar-item">
            <button class="button" title="Remember Note">
                <span class="icon">
                    <i class="fa fa-marker" />
                </span>
            </button>
        </div>
        <div class="navbar-item">
            <button class="button" title="Remember Photo">
                <span class="icon">
                    <i class="fa fa-camera" />
                </span>
            </button>
        </div>
        <div class="navbar-item">
            <button class="button" title="Remember Audio">
                <span class="icon">
                    <i class="fa fa-microphone" />
                </span>
            </button>
        </div>
        <div class="navbar-item">
            <button class="button" title="Remember Video">
                <span class="icon">
                    <i class="fa fa-video" />
                </span>
            </button>
        </div>
        <div class="navbar-item">
            <button class="button" title="Remember URL">
                <span class="icon">
                    <i class="fa fa-link" />
                </span>
            </button>
        </div>
        <div class="navbar-item">
            <button class="button" title="Remember File">
                <span class="icon">
                    <i class="fa fa-file" />
                </span>
            </button>
        </div>
    </div>
</div>

// pwa/src/components/Toolbar.vue
<template>
  <div class="container">
    <div class="field is-grouped">
        <div class="navbar-item">
          <button class="button">
            <span class="icon">
              <i class="fa fa-marker"></i>
            </span>
          </button>
        </div>
        <div class="navbar-item">
          <button class="button">
            <span class="icon">
              <i class="fa fa-camera"></i>
            </span>
          </button>
        </div>
        <div class="navbar-item">
          <button class="button">
            <span class="icon">
              <i class="fa fa-microphone"></i>
            </span>
          </button>
        </div>
        <div class="navbar-item">
          <button class="button">
            <span class="icon">
              <i class="fa fa-video"></i>
            </span>
          </button>
        </div>
        <div class="navbar-item">
          <button class="button">
            <span class="icon">
              <i class="fa fa-link"></i>
            </span>
          </button>
        </div>
        <div class="navbar-item">
          <button class="button">
            <span class="icon">
              <i class="fa fa-file"></i>
            </span>
          </button>
        </div>
    </div>
  </div>
</template>
