// pwa/src/components/Navbar.vue
<template>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="https://memori.link">
        <img :src="require('../assets/icons/icon-192.png')">
        <i>Never Forget</i>
      </a>
    </div>
    <div class="navbar-menu">
      <div class="navbar-start">

      </div>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <button class="button is-light">Log Out</button>
        </div>
      </div>
    </div>
  </nav>
</template>

<script lang="ts">
</script>

// pwa/src/Navbar.svelte

<div>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="https://memori.link">
                <img src="/icons/icon-192.png" alt="Memori : Never Forget"/>
                <i>Never Forget</i>
            </a>
        </div>
        <div class="navbar-menu">
            <div class="navbar-start" />
        </div>
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <button class="button is-light">Log Out</button>
                </div>
            </div>
        </div>
    </nav>
</div>
